name: BetterPingCommand
version: '${project.version}'
main: dev.goldenedit.betterpingcommand.BetterPingCommand
api-version: '1.20'
commands:
  ping:
    description: "Displays your ping."
    permission: betterping.ping
    usage: /<command>
    aliases: [ latency ]